function(cellworld_add_custom_icon)
    set(file_number 0)
    foreach(f ${ARGN})
        set(icon_file "custom-icon-${file_number}.png")
        configure_file(${f} ${CMAKE_CURRENT_BINARY_DIR}/icons/${icon_file} COPYONLY)
        math(EXPR icon_number "${file_number}")
        message("Configuring ${f} as custom icon ${icon_number}")
        math(EXPR file_number "${file_number}+1")
    endforeach()
endfunction()
