#!/bin/bash
index=$(params i-index "-" "$@")
file=$(params f-file "-" "$@")
json=$(params j-json "[' ']" "$@")
return_value=$(params v-value "value" "$@")
lines=$(params l-lines "no" "$@")
output="print(json.dumps($return_value) if isinstance($return_value,dict) or isinstance($return_value,list) else $return_value)"
value="value"
if [ "$lines" != "no" ]; then
  value="value_array"
  output="[ $output for value in value_array ]"
fi

if [ "$file" == "-" ]; then
  python3 -c "import json; $value = json.loads('$json'); $output"
else
  if [ "$file" == "stdin" ]; then
    python3 -c "import sys, json; $value = json.load(sys.stdin); $output"
  else
    python3 -c "import sys, json; $value = json.load(sys.stdin); $output" < "$file"
  fi
fi
